logging:
  config: classpath:log4j2.xml
mybatis-plus:
  mapper-locations: classpath:mapper/**/*Mapper.xml
  global-config:
    db-config:
      field-strategy: not_empty
      id-type: auto
      db-type: mysql
    banner: false
    super-mapper-class: org.crown.framework.mapper.BaseMapper
  type-enums-package: org.crown.enums
  type-aliases-package: org.crown.projects.**.model.entity,org.crown.projects.**.model.dto
server:
  port: 8089
  servlet:
    context-path: /
spring:
  servlet:
    multipart:
      maxFileSize: "100MB"
      maxRequestSize: "10MB"
  jackson:
    time-zone: GMT+8
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
      FAIL_ON_EMPTY_BEANS: false
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
    default-property-inclusion: non_null
    mapper:
      PROPAGATE_TRANSIENT_MARKER: true
    parser:
      ALLOW_BACKSLASH_ESCAPING_ANY_CHARACTER: true
  liquibase:
    enabled: false
  datasource:
    url: jdbc:p6spy:mysql://192.168.1.112:3306/yihe?characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: boostech
    password: admin
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    hikari:
      auto-commit: false
      connection-timeout: 30000
      idle-timeout: 25000
      login-timeout: 5
      max-lifetime: 30000
      read-only: false
      validation-timeout: 3000
      maximum-pool-size: 15
      minimum-idle: 10
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false
  aop:
    auto: true
    proxy-target-class: true
qiniu:
  accessKey: 4Xgx3ORBO0oMGaOTe4qNZLE3R9yK_X1irnadwNEL
  secretKey: SGEQW42gGP09ecTgWEa65n1_H81XsXQ-EadDRh6z
  bucket: boostech
  prefix: q0lhgg606.bkt.clouddn.com
wx:
  appId: wxc70f297a49a01a6e
  secret: d99213ebececcf8d9c0fbcd47461a627
  mchId: 1411135402